### ISSUE TITLE
Add unit tests and CI

### ISSUE THREAD

**Issue by mjuric** [astronomy-commons/genesis-client#1]
Think about how to unit test this package -- it's non-trivial as `genesis.streaming` requires a running Kafka instance. There are probably a few parts to this:

- [x] Choose and set up CI
- [x] Find a way to install/run Kafka inside the CI environment
- [x] Write actual unit tests (likely adapt them from demo notebooks)

Some related notes/docs:
* https://github.com/wvanbergen/kafka/blob/master/.travis.yml
* https://github.com/oleksiyk/kafka/blob/master/.travis.yml
* https://github.com/apache/kafka/blob/trunk/.travis.yml
* https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops

**Comment by mjuric** [comment]
Note: one option is to set up a permanent Kafka server with auth on `epyc` (or similar)

**Comment by jbkalmbach** [comment]
I'm interested in helping with this. I'd be starting from scratch with kafka but do know about setting up CI.

**Comment by mjuric** [comment]
@jbkalmbach Thanks Bryce!

Proposal: how about if you started with https://github.com/genesis-platform/genesis-images/issues/4? It's essentially a subset of the problem here (set up CI, run docker containers within CI).

This issue then becomes transferring that know-how here, with Kafka running in the container?

**Comment by spenczar** [comment]
This is done in v1.0.0. We use a Github Action which runs Kafka for integration tests.
