### ISSUE TITLE
Rename genesis-client to `adc-streaming`

### ISSUE THREAD

**Issue by mjuric** [astronomy-commons/genesis-client#15]
`genesis-client` is a rather non-descriptive name for what this library is evolving to -- a light-weight transport-protocol agnostic interface to pub/sub systems commonly used in astronomy. I think it therefore deserves a new name, and I'd propose 'neutrino'.

Pros:
* [ ] Because, just like our library, neutrinos are lightweight and fast
* [ ] Because it will be easier to remember than genesis-client
* [ ] Because the tagline could be "neutrino - [free streaming](https://en.wikipedia.org/wiki/Free_streaming)", which makes the inner physicist in me very happy :-)
* [ ] `neutrino` is available on `conda-forge`
* [ ] Because it _might_ be possible to get [neutrino on PyPI](https://pypi.org/project/neutrino/), as it seems abandoned.

Cons:
* [ ] `neutrino` is not descriptive of the underlying functionality. Reminds me how OpenStack has all weirdly named projects (nova, swift, keystone, neutron, ...) and I can never remember which one is which.
* [ ] We may not get the PyPI name, and would need to come up with something like `neutrino-lib` or similar.
* [ ] Google-ability of just "neutrino" is not ideal.

**Comment by spenczar** [comment]
I think that this thing should have a more descriptive name. It's going to operate as relatively low-level glue, used to make higher-level clients which most people _actually_ use. That means that branding is not very important, but clarity for someone debugging their higher-level client or trying to make sense of an error message is much more important.

With a name like `neutrino`, I think those might be confusing for the bewildered user who is told that the neutrinos won't accept their authentication mechanism. If it has a name closer to what it does ("data-stream-connector", "alertstreams", "pubsubber", or something) then it may be a lot clearer.

I don't think the choice of name matters a ton though, and "fun" is a pretty good reason to pick neutrino, in my book.

**Comment by spenczar** [comment]
Mentioned in https://github.com/astronomy-commons/genesis-client/pull/18/files#r395461693 - when we change the name, we should also take the chance to change Author metadata in setup.py, doc configs, etc.

**Comment by mjuric** [comment]
@spenczar et al.: very good points!

How about `adc-streaming`?

Usage:
- `pip install adc-streaming`
- `import adc.streaming`

Rationale:
- [ ] `adc` stands for "Astronomy Data Commons", which is the umbrella project under which we're building/(extracting from LSST) broadly reusable cloud-based astronomy infrastructure (that's what https://github.com/astronomy-commons org is about)
- [ ] `import adc.streaming` seems reasonably descriptive.
- [ ] We've already grabbed `adc` on PyPI, which could be made into an umbrella metapackage to install various ADC subprojects (i.e., `pip install adc` gets you everything from AXS/Spark support to streaming).
- [ ] There could be confusion with folks caring about A/D converters, but we can manage :)

**Comment by spenczar** [comment]
I really like `adc-streaming`, yes!

**Comment by mjuric** [comment]
OK, I'm calling it -- let's call it `adc-streaming` (`import adc.streaming`), as discussed in https://github.com/astronomy-commons/genesis-client/issues/15#issuecomment-602422026. 

@spenczar, leaving the implementation fun to you :).
