### ISSUE TITLE
Support authentication in `genesis.streaming`

### ISSUE THREAD

**Issue by mjuric** [astronomy-commons/genesis-client#3]
Support authenticating Kafka authentication. Something like:

```
with gs.open("kafka://genesis.alerts.wtf/small", user='mjuric', password=...) as stream:
    ...
```

Think whether there's a way to make this API safer (to discourage users from hardcoding the password into their code).

**Comment by ebellm** [comment]
Username/password is much more convenient for typical users than kerberos stuff, but Christopher's work suggests we need the latter to implement authorization in Kafka (which I think is essential).  Maybe there's a way to deal ourselves with the kerberos, upstream from the client?

**Comment by mjuric** [comment]
Adding a keyword arg such as 'type="kerberos"', with kwargs 'principal=' and 'keytab=' may be a way to support it. E.g.:

```
with gs.open("kafka://genesis.alerts.wtf/small", type='kerberos', principal='mjuric', keytab=...) as stream:
    ...
```
and maybe a shorthand form:
```
with gs.open("kafka+krb://mjuric@genesis.alerts.wtf/small", keytab=...) as stream:
    ...
```
N.b., to make Kafka integrate with CILogon (and LSST's auth infrastructure), we'll likely need to develop a LDAP auth module for Kafka. Confluent [already has one](https://docs.confluent.io/current/security/ldap-authorizer/introduction.html), but it's not open source.

**Comment by mjuric** [comment]
I merged an initial implementation of this in PR #5 -- for now auth type and credentials are specified via librdkafka config values; I'm leaving this open to remember to implement a more user friendly API (as discussed above).

**Comment by myNameIsPatrick** [comment]
I'm thinking a cleaner solution to this may be to adopt an approach similar to how the requests library does authentication: https://requests.readthedocs.io/en/master/user/authentication/

For example, some basic auth style SASL authentication could be done as follows:

```
auth = SASLAuth('test', 'test-pass', ssl_ca_location='/path/to/cacert.pem')
with gs.open("kafka://genesis.alerts.wtf/small", auth=auth) as stream:
    ...
```

with some reasonable defaults, i.e. `ssl` enabled and without a cert specified, looks in the default CA path.

This would be a simple class setting up librdkafka-style configuration which when called, returns back that configuration that can be used for the client.

**Comment by mjuric** [comment]
I like this as a generic approach. Any comments from @ebellm?

**Comment by ebellm** [comment]
Seems like a fine approach to me.
