### ISSUE TITLE
Version for new release?

### ISSUE THREAD

**Issue by myNameIsPatrick** [astronomy-commons/genesis-client#50]
@cnweaver and I would like a new release to grab some of the latest features from master. I can do the work to put out a new release, but wanted to check that this would correspond with a minor version bump or major? It's not clear to me what the API changes introduced by the work @cnweaver added and how much of this is backwards incompatible.

**Comment by cnweaver** [comment]
It is backwards incompatible enough to quite noticeably break code written against the old interface, unfortunately: https://github.com/scimma/hop-client/issues/158 . 
Whether you want to treat that as a major version change or not is mostly up to how you want to interpret the version number.

**Comment by myNameIsPatrick** [comment]
I have no preference personally on whether we go with 2.0.0 or 1.3.0. Following SemVer to the letter would be nice in principle. Do you have a preference for one or the other, @spenczar?

**Comment by spenczar** [comment]
Yes, since this is a breaking change, it should be `2.0.0`, I think.
