### ISSUE TITLE
Expose topic key for read/writing messages

### ISSUE THREAD

**Issue by myNameIsPatrick** [astronomy-commons/genesis-client#7]
One feature that would be desirable for myself is to publish messages with a given topic key, and listen to messages with a set of topic keys.

This would allow one to partition messages across the broker based on a given topic and filter incoming messages as desired. In doing so, we can filter messages without ever having to receive them or having to provide a filter function at the client level. Ultimately that comes down to how you store messages into Kafka, either multiple keys for topics with a common theme, or multiple topics.

**Comment by shereenElSayed** [comment]
When I receive a message, I would like to get additional message information with it, i.e. (topic, key, ...etc.) This will help direct messages according to their topic for subscribers to all topics.

**Comment by myNameIsPatrick** [comment]
Something I was thinking about here is to maybe expose additional information about the message in the filtering stage (`msg.value`, `msg.topic`, `msg.key`), but then just return `msg.value` when returned from the client.

Another idea is to provide an option to provide similar properties as the original message when returned from the client, but not have this by default. I expect most users to not needing it, but some may be disappointed by the loss of information.

Part of the problem I expect is that the confluent-kafka Message object isn't pickleable, so this needs to be unpacked in a way that is sensible before it's possibly sent out to a pooling object. Probably a data class or a named tuple.

**Comment by mjuric** [comment]
How about if we add a boolean `metadata` argument to `open`. If `metadata=True`, then at any place where a record would be return, we instead return a `(record, metadata)` tuple, where the contents of `metadata` will be transport specific. For Kafka, the returned metadata would be a `(topic, partition, offset)` tuple (or maybe named tuple?).

Mock example:
```
import genesis.streaming as gs

with gs.open("kafka://localhost/test1,test2,test3", metadata=True) as stream:
    for (msg, meta) in stream(...):
        if meta.topic == 'test2':
            ...
```

Thoughts?

**Comment by myNameIsPatrick** [comment]
I'm good with that plan, I like it better than what I was thinking.
