### ISSUE TITLE
Versions from untagged commits run into SemVer issues

### ISSUE THREAD

**Issue by myNameIsPatrick** [astronomy-commons/genesis-client#8]
If I try to install the genesis client from master rather than a tag, I'll run into the issue where the version resolves to one older than the tagged version:

```
ERROR: scimma-client 0.0.5.dev31+g9996870 has requirement adc>=0.0.2, but you'll have adc 0.0.2.dev5+878b4d0 which is incompatible.
```

This is because dev tags with the same version are considered to be older than the clean version. setuptools_scm handles this by incrementing the minor or point release by one.

**Comment by spenczar** [comment]
I ran into this as well. I modified `scimma-client`'s `setup.py` to ask for `adc >= 0.0.2.dev0`, but that doesn't really seem right. #10 looks more reasonable.
